version: '3'
services:
  mariadb:
    container_name: ejbca-db
    hostname: ejbca-db
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./db
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=foo12345
      - MYSQL_DATABASE=ejbca
      - MYSQL_USER=ejbca
      - MYSQL_PASSWORD=foo12345
    volumes:
      - './db/datadir:/var/lib/mysql'
    networks:
      ejbca-net:
  ejbca:
    container_name: ejbca-node1
    hostname: ejbca-node1
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./caserver
    environment:
      - PROXY_HTTP_BIND=0.0.0.0
      - INITIAL_ADMIN=;PublicAccessAuthenticationToken:TRANSPORT_ANY;
      - DATABASE_JDBC_URL=jdbc:mysql://mariadb:3306/ejbca?characterEncoding=UTF-8
      - DATABASE_USER=ejbca
      - DATABASE_PASSWORD=foo12345
    depends_on:
      - mariadb 
    networks:
      ejbca-net:
  nginx:
    container_name: nginx1
    hostname: nginx1
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/tls-test-secret.crt:/etc/ssl/tls-test-secret.crt'
      - './nginx/tls-test-secret.key:/etc/ssl/private/tls-test-secret.key:ro'
    networks:
      ejbca-net:
  web:
    container_name: crlweb
    hostname: crlweb
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./web
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - './web/conf.d:/etc/nginx/conf.d'
      - './web/src:/var/www/html'
    networks:
      ejbca-net:
  

networks:
  ejbca-net:
    driver: bridge
    ipam:
      driver: default